---
# This is nearly identical to `python-tests.yml` and both should be updated in tandem where appropriate.
# This file adds a service for a postgres db.
name: python-tests-with-db

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.12"

      cache-dependency-path:
        type: string
        default: "pyproject.toml"

      enable-lfs:
        type: boolean
        default: false

      checkout-fetch-depth:
        type: number
        default: 1

    secrets:
      package-repo:
        description: "Package repository authentication token"
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: database
        ports:
          - "61900:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: "Initialise database one schema"
        run: psql -c "create schema one" postgresql://user:password@localhost:61900/database
      - name: "Initialise database two schema"
        run: psql -c "create schema two" postgresql://user:password@localhost:61900/database
      - name: "Initialise database three schema"
        run: psql -c "create schema three" postgresql://user:password@localhost:61900/database
      - name: "Checkout code"
        uses: actions/checkout@v3
        with:
          lfs: ${{ inputs.enable-lfs }}
          fetch-depth: ${{ inputs.checkout-fetch-depth }}

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: ${{ inputs.cache-dependency-path }}

      - name: "Install dependencies"
        env:
          PIP_EXTRA_INDEX_URL: ${{ secrets.package-repo }}
        run: |
          make init-dev

      - name: "Run tests"
        run: |
          make pytest
